name: Live Page pushen

on: [push, workflow_dispatch]

jobs:
  deploy-live-page:
    name: alpenblick-saasfee.ch

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.13
      with:
          hugo-version: 'latest'
          extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: RetoZ/alpenblick-live
        publish_branch: master
        publish_dir: ./public
        cname: www.alpenblick-saasfee.ch